server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO

#spring: в мануале
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

spring:
  # Настраиваем подключение к базе данных
  datasource:
#    default: ${APP_ENV}  #${APP_ENV} #development

#    development:
      url: "jdbc:h2:./taskManager"
      username: sa
      password: sa
      driverClassName: org.h2.Driver

#    production:
#      username: ${PGUSER} #${JDBC_DATABASE_USERNAME}
#      password: ${PGPASSWORD} #${JDBC_DATABASE_PASSWORD}
#      url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE} #${JDBC_DATABASE_URL}

  # Настраиваем инструмент Liquibase
  # Указываем путь к основному файлу миграции
  liquibase:
    change-log: classpath:src/main/resources/db/changelog/db.changelog-master.yaml

  # Настраиваем консоль Н2
  # Это позволит нам открыть её в браузере по указанному пути
  h2:
    console:
      enabled: true
      # Указываем путь, по которому будет окрываться консоль
      path: /h2console/
      settings:
        web-allow-others: true

#  скопировал из мануала спринг
  jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect