server:
  port: ${PORT:5000}

logging:
  level:
    root: INFO

spring:
  # Настраиваем подключение к базе данных
  datasource:
    default: ${APP_ENV}  #${APP_ENV} #development

    development:
      username: sa
      password: sa
      url: "jdbc:h2:./taskManager"

    production:
      username: ${PGUSER} #${JDBC_DATABASE_USERNAME}
      password: ${PGPASSWORD} #${JDBC_DATABASE_PASSWORD}
      url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE} #${JDBC_DATABASE_URL}

  # Настраиваем инструмент Liquibase
  # Указываем путь к основному файлу миграции
  liquibase:
    change-log: classpath:src/main/resources/db/changelog/db.changelog-master.yaml  # в ДЗ ОРМ db/changelog/changelog-master.xml

  # Настраиваем консоль Н2
  # Это позволит нам открыть её в браузере по указанному пути
  h2:
    console:
      enabled: true
      # Указываем путь, по которому будет окрываться консоль
      path: /h2console/
      settings:
        web-allow-others: true