server:
  port: ${PORT:8080}

spring:
  # Настраиваем подключение к базе данных
  datasource:
    url: jdbc:h2:./taskManager
    username: sa
    password: sa
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

# Настраиваем консоль Н2
# Это позволит нам открыть её в браузере по указанному пути
h2:
  console:
    enabled: true
      # Указываем путь, по которому будет окрываться консоль
    path: /h2console/
    settings:
      web-allow-others: true