logging:
  level:
    root: INFO

spring:
  application:
    name: taskManager

  profiles:
    active: ${APP_ENV:dev}
  # Настраиваем инструмент Liquibase
  # Указываем путь к основному файлу миграции
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    show-sql: true #Егор
    hibernate.ddl-auto: validate #Егор