logging:
  level:
    root: INFO

spring:
  # Настраиваем инструмент Liquibase
  # Указываем путь к основному файлу миграции
  liquibase:
    change-log=classpath:db.changelog/db.changelog-master.yaml
  # было change-log=classpath:resources/db/changelog/db.changelog-master.yaml